name: CI

on:
  push:
    branches:
      - main
      - feature/image-feed/cache-feed-use-case

jobs:
  # Первое задание: Сборка и тестирование для iOS (EssentialApp)
  build-and-test-ios:
    runs-on: macos-14
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.0.app

      - name: Get simulators list
        run: xcrun simctl list

  #     - name: Build and Test iOS
  #       run: |
  #         xcodebuild clean build test \
  #         -workspace EssentialApp.xcworkspace \
  #         -scheme "CI_iOS" \
  #         CODE_SIGN_IDENTITY="" \
  #         CODE_SIGNING_REQUIRED=NO \
  #         -sdk iphonesimulator \
  #         -destination "platform=iOS Simulator,name=iPhone 15,OS=18.1"
  #
  # # Второе задание: Сборка и тестирование для macOS
  # build-and-test-macos:
  #   runs-on: macos-14
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Select Xcode
  #       run: sudo xcode-select -switch /Applications/Xcode_16.0.app
  #
  #     - name: Build and Test macOS
  #       run: |
  #         xcodebuild clean build test \
  #         -project EssentialFeed.xcodeproj \
  #         -scheme "CI_macOS" \
  #         CODE_SIGN_IDENTITY="" \
  #         CODE_SIGNING_REQUIRED=NO \
  #         -sdk macosx \
  #         -destination "platform=macOS"
  #
  # # Третье задание: Сборка и тестирование EssentialFeed (ожидает выполнения первых двух заданий)
  # build-and-test-essentialfeed:
  #   runs-on: macos-14
  #   needs:
  #     - build-and-test-ios
  #     - build-and-test-macos
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Select Xcode
  #       run: sudo xcode-select -switch /Applications/Xcode_16.0.app
  #
  #     - name: Build and Test iOS EssentialFeed
  #       run: |
  #         xcodebuild clean build test \
  #         -project EssentialFeed.xcodeproj \
  #         -scheme "EssentialFeed" \
  #         CODE_SIGN_IDENTITY="" \
  #         CODE_SIGNING_REQUIRED=NO \
  #         CODE_SIGNING_ALLOWED=NO \
  #         -sdk iphonesimulator \
  #         -destination "platform=iOS Simulator,name=iPhone 15,OS=18.1"


          # SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
