name: CI

# Триггеры, определяющие, когда запускать workflow
on:
  push:
    branches:
      - main
      - feature/image-feed/cache-feed-use-case

jobs:
  # Название задания
  build-and-test:
    # Тип runner'а
    runs-on: macos-14

    # Максимальное время выполнения задания (в минутах)
    timeout-minutes: 5

    # Шаги выполнения
    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Выбор версии Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.0.app

      # Шаг 3: Проверка доступных симуляторов
      - name: Get simulators list
        run: xcrun simctl list

      # Шаг 4: Сборка и тестирование для macOS
      - name: Build and Test macOS
        run: |
          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI_macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -sdk macosx \
          -destination "platform=macOS"
          # SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"

      # Шаг 5: Сборка и тестирование для iOS
      - name: Build and Test iOS
        run: |
          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI_iOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,id=9D2136F3-295E-4A21-81F0-739A21996804"
          # SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
